# Generated by Django 3.0.2 on 2020-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
